trigger:
  - main

pool:
  vmImage: ubuntu-latest


variables:
  - name: DOCKERIMAGENAME
    value: app-cicd
stages:
  # - stage: BuildGradle
  #   jobs:
  #   - job:
  #     displayName: Gradlew build 
  #     steps:
  #       - task: Gradle@2
  #         inputs:
  #           workingDirectory: ''
  #           gradleWrapperFile: 'gradlew'
  #           gradleOptions: '-Xmx3072m'
  #           javaHomeOption: 'JDKVersion'
  #           jdkVersionOption: '1.8'
  #           jdkArchitectureOption: 'x64'
  #           publishJUnitResults: true
  #           testResultsFiles: '**/TEST-*.xml'
  #           tasks: 'build'
  - stage: PushDockerImage
    jobs:
      - job:
        displayName: Build Dockerfile
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'azuredevops'
              repository: 'gikuluca/cicddevops.azurecr.io'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: '$(DOCKER_IMAGE_NAME)$(Build.BuildId)'
  - stage: Deploy to k8s dev
    jobs:
      - job:
        variables:
          - name: BUILDID
            value: $(Build.BuildId)
        displayName: Deploy to kube
        steps:
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'k8s-dev-azure'
              namespace: 'dev'
              manifests: 'deploy.yaml'
          

            