trigger:
  - main

pool:
  name: 'Ubuntu-latest'

environment: 'dev'
  
stages:
  - stage: Build
    jobs:
      - job:
        displayName: Build gradle
        steps:
          - script: |
              ls
