trigger:
  - main

pool:
  name: 'Ubuntu-latest'

  
stages:
  - stage: BuildGradle
    jobs:
    - job:
      displayName: Gradlew build 
      steps:
        - task: Gradle@3
          inputs:
            gradleWrapperFile: 'gradlew'
            tasks: 'build'
            publishJUnitResults: true
            testResultsFiles: '**/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            sonarQubeRunAnalysis: false
            spotBugsAnalysis: false
  - stage: PushDockerImage
    jobs:
      - job:
        displayName: Build Dockerfile
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'azuredevops'
              repository: 'cicddevops.azurecr.io'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: '$(Build.BuildId)'
            